[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~1.0.0"

[[override]]
  revision = "5db89f0ca68677abc5eefce8f2a0a772c98ba52d"
  name = "github.com/docker/distribution"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  version = "kubernetes-1.13.3"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.3"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.3"

[[override]]
  version = "kubernetes-1.13.3"
  name = "k8s.io/api"

[[override]]
  version = "kubernetes-1.13.3"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.3"

[[override]]
  name = "github.com/onsi/ginkgo"
  version = "v1.7.0"

[[override]]
  name = "github.com/onsi/gomega"
  version = "v1.4.3"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
