---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
data:
  # Required if provisionVolume is set to false
  userID: YWRtaW4=  # BASE64-ENCODED-VALUE
  userKey: YWRtaW4=  # BASE64-ENCODED-VALUE

  # Required if provisionVolume is set to true
  adminID: YWRtaW4=  # BASE64-ENCODED-VALUE
  adminKey: YWRtaW4=  # BASE64-ENCODED-VALUE
